### ISSUE TITLE
not implemented for: just-contaminaited

### ISSUE THREAD

**Issue by ChristianKammler** [lvanhee/COVID-sim#116]
While doing runs for the smart testing scenario, I encoutered the following error. Unfortunately, I wasn't present the whole time, so I can't tell at which specific run it occured. 
![WhatsApp Image 2020-04-28 at 21 10 22](https://user-images.githubusercontent.com/32814408/80529117-42ae2f00-8997-11ea-86bd-12c330716147.jpeg)

**Comment by ChristianKammler** [comment]
This doesn´t happen everytime however. I had at least thirty runs in a row where it didn´t happen during a batch run. Prior to this it happened to me one time where within 8 concecutive runs. However, this runs have been set-up manually each.

**Comment by lvanhee** [comment]
Ok. Could you please share some csv with me so I can replay it?

**Comment by kurtk92** [comment]
this is the same bug that i mailed you about Lois, so i guess this is fixed now right?

**Comment by lvanhee** [comment]
Possibly but not certainly. The bug from Christian seems to be fired from a different place; though both might be solved by the same fix. Let's wait and see if Christian still faces the issue.
