### ISSUE TITLE
No file country-specific-data.csv

### ISSUE THREAD

**Issue by rmellema** [lvanhee/COVID-sim#133]
I'm assuming @kurtk92 forgot to add this one, which makes Netlog throw an error on setup. 

Stack-trace:
```
The file /Users/renem/Source/COVID-sim/simulation_model/country-specific-data.csv cannot be found
error while observer running FILE-AT-END?
  called by procedure LOAD-NATIONS-HOFSTEDE-DIMENSION-SCORES (/Users/renem/Source/COVID-sim/simulation_model/country_specific_features/cultural_model.nls)
  called by procedure SETUP-PERSON-VALUES-AND-NEEDS (/Users/renem/Source/COVID-sim/simulation_model/country_specific_features/cultural_model.nls)
  called by procedure SETUP (/Users/renem/Source/COVID-sim/simulation_model/setup.nls)
  called by procedure STARTUP
  called by procedure __EVALUATOR
```

**Comment by kurtk92** [comment]
yes so sorry! i made a directory "country_specific_features" in the simulation_model folder wherein Bart and I will be adding modules to enhance the country-specificity of the assocc model

i redefined the path to the country-specific-data.csv file as follows:
file-open "country_specific_features/country-specific-data.csv" (see scenarios.nls)

very stupid of me to not check whether it would work upon setup, will not make that mistake again.

**Comment by kurtk92** [comment]
i fixed this now

**Comment by rmellema** [comment]
The file is still not in the repository though, so this still throws errors for any country other than "Custom".

**Comment by kurtk92** [comment]
wtf i put the csv in the directory and pushed it back up but you're right it still isnt in there, i will try again

**Comment by rmellema** [comment]
By default git ignores .csv files in this directory, so you need to explicitly add it in whatever git client you are using.
