### ISSUE TITLE
Workplaces have infinite stock

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#33]
But they shouldn't and get more capital instead. See screenshot:

![image](https://user-images.githubusercontent.com/59364209/77850828-5e29ec80-71d5-11ea-894d-eed8cd698643.png)

**Comment by lgludescher** [comment]
This was a bug fixed in last changes. Stocks were growing indefinitely because workers could perform work (and produce goods) even if they didn't receive payment for that. Now it's working properly.

**Comment by MelchiorUU** [comment]
Unfortunately it still happens:

![image](https://user-images.githubusercontent.com/59364209/77861407-10cd6f80-7215-11ea-87f8-8d8e91ad82bb.png)

There are 10 workplaces, total is over 5000.

**Comment by ChristianKammler** [comment]
Yes this can be possible. Slider is for shops as "max-stock-of-goods-in-a-shop"
Shops unequal to workplaces.

Gonna look into the code now to identify the limit.

**Comment by lgludescher** [comment]
This is expected since no maximum capacity was established for workplaces as previously discussed via email. So, this is not a bug anymore, but it's something to be implemented.

**Comment by lvanhee** [comment]
Hello,
Has this issue been solved, please?
